### ISSUE TITLE
Converting between the same basis

### ISSUE THREAD

**Issue by DanielVandH** [JuliaApproximation/SemiclassicalOrthogonalPolynomials.jl#110]
https://github.com/JuliaApproximation/SemiclassicalOrthogonalPolynomials.jl/blob/54e43e480dbb512010b1f3d188300549c3870674/src/SemiclassicalOrthogonalPolynomials.jl#L266

Is there a technical reason why we can't just return `I` here? The `SymTridiagonal` causes the bandwidth of further multiplications to be increased by 1 on each side for example, if chaining connections where the last connection could just be the identity.

**Comment by dlfivefifty** [comment]
@TSGut wrote that code

I'd return `Eye{T}(∞)`

**Comment by TSGut** [comment]
There is a reason but it's fine to change it as long as you test it well. 

The reason is that in multiple contexts `jacobimatrix` and things using them assume that the data structure is SymTridiagonal. If you return an object of different type in some situations it will likely mean special casing those functions or overloading them to also work with other types.

**Comment by DanielVandH** [comment]
Think this has now changed in the latest PR, so closing
